package com.cars.cardealership.mybatis.dao;

import com.cars.cardealership.mybatis.model.Make;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface MakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MAKE
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MAKE
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    int insert(Make record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MAKE
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    Make selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MAKE
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    List<Make> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MAKE
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    int updateByPrimaryKey(Make record);
}