package com.cars.cardealership.mybatis.dao;

import com.cars.cardealership.mybatis.model.Shop;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    List<Shop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    int updateByPrimaryKey(Shop record);
}