package com.cars.cardealership.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.CARMODEL
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    private String carmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MAKE_ID
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    private Long makeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.CARMODEL
     *
     * @return the value of PUBLIC.CAR.CARMODEL
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    public String getCarmodel() {
        return carmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.CARMODEL
     *
     * @param carmodel the value for PUBLIC.CAR.CARMODEL
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    public void setCarmodel(String carmodel) {
        this.carmodel = carmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MAKE_ID
     *
     * @return the value of PUBLIC.CAR.MAKE_ID
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    public Long getMakeId() {
        return makeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MAKE_ID
     *
     * @param makeId the value for PUBLIC.CAR.MAKE_ID
     *
     * @mbg.generated Sat Apr 02 18:54:51 EEST 2022
     */
    public void setMakeId(Long makeId) {
        this.makeId = makeId;
    }
}